apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-sr-master-init-scripts
data:
  1_setup.sh: |-
    #!/bin/bash
    set -e
    
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE ROLE $REPL_ROLENAME LOGIN REPLICATION PASSWORD '$REPL_PASSWORD';
    EOSQL

    pgbench -p 5432 -i