apiVersion: v1
kind: Service
metadata:
  name: postgres-lr-master-lb
spec:
  type: LoadBalancer
  selector:
    app: postgres-lr-master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432