apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-lr-slave
  labels:
    app: postgres-lr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-lr-slave
  template:
    metadata:
      labels:
        app: postgres-lr-slave
    spec:
      initContainers:
      - name: setup
        image: postgres:12
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: REPL_ROLENAME
          valueFrom:
            secretKeyRef:
              name: repl
              key: rolename
        - name: REPL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: repl
              key: password
        command:
        - sh
        - -c
        - |
          echo "Start initContainers"

          if [ -e /tmp/config/postgresql.conf ]; then
            echo "Copy postgresql.conf which inherit from configmap"
            cp /tmp/config/postgresql.conf /var/lib/postgresql/config/
          else
            echo "Skipping postgresql.conf preparetion"
          fi

          echo "End initContainers"
        volumeMounts:
        - mountPath: /var/lib/postgresql/config
          name: config
        - mountPath: /tmp/config
          name: config-files
      containers:
      - name: postgres
        image: postgres:12
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: REPL_ROLENAME
          valueFrom:
            secretKeyRef:
              name: repl
              key: rolename
        - name: REPL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: repl
              key: password
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/
          name: init-scripts
        - mountPath: /var/lib/postgresql/config
          name: config
        args: 
        - "-c"
        - "config_file=/var/lib/postgresql/config/postgresql.conf"
      volumes:
      - name: init-scripts 
        configMap: 
          name: postgres-lr-slave-init-scripts
          items:
          - key: 1_setup.sh
            path: 1_setup.sh
          - key: 2_pgbench_tables.sh
            path: 2_pgbench_tables.sh
      - name: config
        emptyDir: {}
      - name: config-files
        projected:
          sources:
          - configMap: 
              name: postgres-lr-slave-postgres-conf
              items:
              - key: postgresql.conf
                path: postgresql.conf