apiVersion: v1
kind: Service
metadata:
  name: postgres-lr-slave-lb
spec:
  type: LoadBalancer
  selector:
    app: postgres-lr-slave
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432